### ISSUE TITLE
Would you use https://pub.dev/packages/flutter_data to reduce local storage boiler plate.

### ISSUE THREAD

**Issue by Prn-Ice** [VictorUvarov/provider_architecture_template#36]
Recently heard about [this](https://pub.dev/packages/flutter_data) package and I'm a little skeptical. It seems to have promise but I would like to know your opinion and also if you would ever consider using it in the template.

**Comment by VictorUvarov** [comment]
I've seen this package mentioned on the slack. I glanced at it a bit, but haven't run any example code yet. However you should only add a dependency to your project if it helps you save a lot of time and headache, because each dependency will have to be managed, updated, and maybe forked because a feature you need is not there. I'll take a look at it when I get a chance.

**Comment by Prn-Ice** [comment]
I personally like having control over the model and data storage like you do in yours so I'll stick with that. Thanks.
