### ISSUE TITLE
Similarity between Repository folder and Services folder

### ISSUE THREAD

**Issue by myklll** [VictorUvarov/provider_architecture_template#54]
@VictorUvarov  Hi, Thanks for this lovely project, it has really helped me. I'd love on opinion on both the `repositories` and `services` folder in the structure.

1. What would you say is the difference? What made you categorize something e.g posts under a repository rather than a service.

2. In a situation where you have a single data source - e.g remote, would you still need a separate `data_source` folder? or would you put it under `services`?

Thanks

**Comment by VictorUvarov** [comment]
1. Here is a good explanation on the difference. https://stackoverflow.com/questions/1440096/difference-between-repository-and-service#1440203

2. Since the view models don't know about how the repository is implemented, it's up to you to decide whether or not you need another abstraction of using a data source. Depends on your application.

**Comment by myklll** [comment]
Thank you so much for the clarification.
